<a href="https://colab.research.google.com/github/Adityahulk/Neural-Machine-Translation/blob/master/pytorch_word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [1]:
import torch
import torchvision
import torch.nn as nn
import torch.functional as F
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
!kaggle datasets download -d watts2/glove6b50dtxt

 84% 57.0M/67.7M [00:00<00:00, 70.5MB/s]
100% 67.7M/67.7M [00:00<00:00, 98.9MB/s]


In [6]:
!unzip glove6b50dtxt.zip

Archive:  glove6b50dtxt.zip
  inflating: glove.6B.50d.txt        


In [7]:
file = open("/content/glove.6B.50d.txt",'r')

In [8]:
i = 0;
for l in file:
  print(l)
  i = i+1
  if(i>100):
    break
  

the 0.418 0.24968 -0.41242 0.1217 0.34527 -0.044457 -0.49688 -0.17862 -0.00066023 -0.6566 0.27843 -0.14767 -0.55677 0.14658 -0.0095095 0.011658 0.10204 -0.12792 -0.8443 -0.12181 -0.016801 -0.33279 -0.1552 -0.23131 -0.19181 -1.8823 -0.76746 0.099051 -0.42125 -0.19526 4.0071 -0.18594 -0.52287 -0.31681 0.00059213 0.0074449 0.17778 -0.15897 0.012041 -0.054223 -0.29871 -0.15749 -0.34758 -0.045637 -0.44251 0.18785 0.0027849 -0.18411 -0.11514 -0.78581

, 0.013441 0.23682 -0.16899 0.40951 0.63812 0.47709 -0.42852 -0.55641 -0.364 -0.23938 0.13001 -0.063734 -0.39575 -0.48162 0.23291 0.090201 -0.13324 0.078639 -0.41634 -0.15428 0.10068 0.48891 0.31226 -0.1252 -0.037512 -1.5179 0.12612 -0.02442 -0.042961 -0.28351 3.5416 -0.11956 -0.014533 -0.1499 0.21864 -0.33412 -0.13872 0.31806 0.70358 0.44858 -0.080262 0.63003 0.32111 -0.46765 0.22786 0.36034 -0.37818 -0.56657 0.044691 0.30392

. 0.15164 0.30177 -0.16763 0.17684 0.31719 0.33973 -0.43478 -0.31086 -0.44999 -0.29486 0.16608 0.11963 -0.41328 -0.423

In [9]:
i = 0;
for l in file:
  print(l.split())
  i = i+1
  if(i>100):
    break
  

['them', '0.64642', '-0.556', '0.47038', '-0.82074', '0.79512', '0.28771', '-0.56426', '0.1463', '-0.52421', '0.021607', '-0.11266', '0.31986', '-0.057542', '-0.23375', '0.63703', '0.3382', '0.4649', '-0.42398', '0.091868', '-0.8804', '0.22077', '0.7127', '0.98196', '-0.033819', '0.31554', '-1.8001', '-0.26003', '-0.37762', '0.85634', '-1.3393', '3.6408', '0.87273', '-0.7923', '-0.51268', '0.14415', '0.55439', '0.1006', '0.13233', '-0.071904', '-0.16399', '-0.089989', '-0.031932', '0.6139', '0.40419', '0.22686', '-0.18974', '-0.55403', '-0.35831', '-0.10995', '-0.447']
['what', '0.45323', '0.059811', '-0.10577', '-0.333', '0.72359', '-0.08717', '-0.61053', '-0.037695', '-0.30945', '0.21805', '-0.43605', '0.47318', '-0.76866', '-0.2713', '1.1042', '0.59141', '0.56962', '-0.18678', '0.14867', '-0.67292', '-0.34672', '0.52284', '0.22959', '-0.072014', '0.93967', '-2.3985', '-1.3238', '0.28698', '0.75509', '-0.76522', '3.3425', '0.17233', '-0.51803', '-0.8297', '-0.29333', '-0.50076', '-0.

In [10]:
i = 0;
for l in file:
  print(l.split()[0])
  i = i+1
  if(i>100):
    break
  

court
say
around
foreign
10
until
set
political
says
market
however
family
life
same
general
–
left
good
top
university
going
number
major
known
points
won
six
month
dollars
bank
2
iraq
use
members
each
area
found
official
sunday
place
go
based
among
third
times
took
right
days
local
economic
countries
see
best
report
killed
held
business
west
does
own
%
came
law
months
women
're
power
think
service
children
bush
show
/
help
chief
saturday
system
john
support
series
play
office
following
me
meeting
expected
late
washington
games
european
league
reported
final
added
without
british
white
history
man
men
became


In [11]:
i = 0;
for l in file:
  print(l.split()[1:-1])
  i = i+1
  if(i>100):
    break
  

['0.13627', '-0.054478', '0.3703', '-0.41574', '0.60568', '-0.42729', '-0.50151', '0.35923', '-0.49154', '0.21827', '-0.15193', '0.52536', '-0.24206', '0.023875', '0.8225', '1.089', '0.98825', '-0.17803', '0.77806', '-1.0647', '-0.28742', '0.50458', '0.21612', '0.65681', '0.34295', '-2.1084', '-0.82557', '-0.31966', '0.87567', '-1.0679', '3.3802', '1.2084', '-1.272', '-0.15921', '-0.25237', '-0.2696', '-0.18756', '-0.35523', '0.084172', '-0.56539', '-0.24081', '0.15926', '0.3287', '0.54591', '0.29897', '0.18948', '-0.57113', '0.17399', '-0.19338']
['-0.059194', '-0.037394', '0.0087116', '-0.14827', '-0.10177', '-0.0087419', '-0.9993', '-0.015026', '-0.62431', '-0.52445', '0.17419', '-0.8848', '-0.38891', '-0.49711', '1.2275', '0.08371', '-1.2629', '-0.57908', '-1.6199', '0.65419', '1.398', '-0.39231', '0.68135', '-0.4766', '-0.70199', '-1.2588', '0.50863', '-0.47468', '-0.038024', '0.82257', '2.9908', '-0.2456', '-1.1063', '-0.27133', '0.056171', '-0.84567', '0.63784', '-0.12177', '0.0

In [12]:
model = {}
i = 0
for l in file:
  word = l.split()[0]
  value = np.array([float(val) for val in l.split()[1:]])
  model[word] = value
  i = i+1
  if(i>100):
    break
  

In [13]:
def glove_model(path):
  model = {}
  file = open(path,'r')

  for l in file:
    line = l.split()
    word = line[0]
    value = np.array([float(val) for val in line[1:]])
    model[word] = value
  
  return model

In [14]:
def glove_vector(path,word):
  model = glove_model(path)
  return model[word]

In [15]:
path = "/content/glove.6B.50d.txt"
word = 'python'
print(glove_vector(path,word))

[ 0.5897   -0.55043  -1.0106    0.41226   0.57348   0.23464  -0.35773
 -1.78      0.10745   0.74913   0.45013   1.0351    0.48348   0.47954
  0.51908  -0.15053   0.32474   1.0789   -0.90894   0.42943  -0.56388
  0.69961   0.13501   0.16557  -0.063592  0.35435   0.42819   0.1536
 -0.47018  -1.0935    1.361    -0.80821  -0.674     1.2606    0.29554
  1.0835    0.2444   -1.1877   -0.60203  -0.068315  0.66256   0.45336
 -1.0178    0.68267  -0.20788  -0.73393   1.2597    0.15425  -0.93256
 -0.15025 ]


In [59]:
model = glove_model(path)

In [17]:
model['it']

array([ 0.61183 , -0.22072 , -0.10898 , -0.052967,  0.50804 ,  0.34684 ,
       -0.33558 , -0.19152 , -0.035865,  0.1051  ,  0.07935 ,  0.2449  ,
       -0.4373  , -0.33344 ,  0.57479 ,  0.69052 ,  0.29713 ,  0.090669,
       -0.54992 , -0.46176 ,  0.10113 , -0.02024 ,  0.28479 ,  0.043512,
        0.45735 , -2.0466  , -0.58084 ,  0.61797 ,  0.6518  , -0.58263 ,
        4.0786  , -0.2542  , -0.14649 , -0.34321 , -0.25437 , -0.44677 ,
        0.12657 ,  0.28134 ,  0.13331 , -0.36974 ,  0.050059, -0.10058 ,
       -0.017907,  0.11142 , -0.71798 ,  0.491   , -0.099974, -0.043688,
       -0.097922,  0.16806 ])

In [18]:
cosine_similarity(model['cat'].reshape(1, -1), model['dog'].reshape(1, -1))

array([[0.92180053]])

In [ ]:
predicted_king_embedding = model['queen'] - model['woman'] + model['man']
cosine_similarity(predicted_king_embedding.reshape(1, -1), model['king'].reshape(1, -1))

array([[0.85888392]])

In [19]:
text = """How that personage haunted my dreams, I need scarcely tell you. On
stormy nights, when the wind shook the four corners of the house and
the surf roared along the cove and up the cliffs, I would see him in a
thousand forms, and with a thousand diabolical expressions. Now the leg
would be cut off at the knee, now at the hip, now he was a monstrous
kind of a creature who had never had but the one leg, and that in the
middle of his body. To see him leap and run and pursue me over hedge and
ditch was the worst of nightmares. And altogether I paid pretty dear for
my monthly fourpenny piece, in the shape of these abominable fancies"""

text = text.replace(',','').replace('.','').lower().split()

In [21]:
corpus = set(text)
corpus_size = len(corpus)

data = []
for i in np.arange(2,len(text)-2):
  sen = [text[i-2],text[i-1],text[i+1],text[i+2]]
  val = text[i]
  data.append((sen,val))

In [32]:
print(data)
print(corpus_size)

[(['how', 'that', 'haunted', 'my'], 'personage'), (['that', 'personage', 'my', 'dreams'], 'haunted'), (['personage', 'haunted', 'dreams', 'i'], 'my'), (['haunted', 'my', 'i', 'need'], 'dreams'), (['my', 'dreams', 'need', 'scarcely'], 'i'), (['dreams', 'i', 'scarcely', 'tell'], 'need'), (['i', 'need', 'tell', 'you'], 'scarcely'), (['need', 'scarcely', 'you', 'on'], 'tell'), (['scarcely', 'tell', 'on', 'stormy'], 'you'), (['tell', 'you', 'stormy', 'nights'], 'on'), (['you', 'on', 'nights', 'when'], 'stormy'), (['on', 'stormy', 'when', 'the'], 'nights'), (['stormy', 'nights', 'the', 'wind'], 'when'), (['nights', 'when', 'wind', 'shook'], 'the'), (['when', 'the', 'shook', 'the'], 'wind'), (['the', 'wind', 'the', 'four'], 'shook'), (['wind', 'shook', 'four', 'corners'], 'the'), (['shook', 'the', 'corners', 'of'], 'four'), (['the', 'four', 'of', 'the'], 'corners'), (['four', 'corners', 'the', 'house'], 'of'), (['corners', 'of', 'house', 'and'], 'the'), (['of', 'the', 'and', 'the'], 'house'),

In [23]:
data[0]

(['how', 'that', 'haunted', 'my'], 'personage')

In [24]:
embedding_length = 20

In [25]:
word_dict = {}
inverse_word_dict = {} 
for i, word in enumerate(corpus):
    word_dict[word] = i
    inverse_word_dict[i] = word

In [26]:
print(word_dict)

{'need': 0, 'kind': 1, 'to': 2, 'ditch': 3, 'shook': 4, 'scarcely': 5, 'wind': 6, 'but': 7, 'stormy': 8, 'thousand': 9, 'pursue': 10, 'over': 11, 'in': 12, 'cove': 13, 'leg': 14, 'nights': 15, 'my': 16, 'expressions': 17, 'forms': 18, 'that': 19, 'knee': 20, 'abominable': 21, 'haunted': 22, 'hedge': 23, 'nightmares': 24, 'cut': 25, 'up': 26, 'altogether': 27, 'his': 28, 'fancies': 29, 'off': 30, 'four': 31, 'monstrous': 32, 'was': 33, 'tell': 34, 'one': 35, 'the': 36, 'you': 37, 'would': 38, 'piece': 39, 'fourpenny': 40, 'surf': 41, 'body': 42, 'cliffs': 43, 'along': 44, 'corners': 45, 'on': 46, 'him': 47, 'worst': 48, 'for': 49, 'never': 50, 'middle': 51, 'he': 52, 'roared': 53, 'how': 54, 'shape': 55, 'at': 56, 'be': 57, 'a': 58, 'now': 59, 'see': 60, 'monthly': 61, 'dreams': 62, 'these': 63, 'leap': 64, 'pretty': 65, 'personage': 66, 'paid': 67, 'creature': 68, 'hip': 69, 'dear': 70, 'and': 71, 'diabolical': 72, 'of': 73, 'run': 74, 'me': 75, 'house': 76, 'who': 77, 'with': 78, 'had

In [27]:
torch.nn.Embedding(corpus_size,embedding_length)(torch.tensor([[1,2,3,4],[1,2,3,4]]))

tensor([[[ 9.8835e-04, -8.6426e-01, -1.4417e+00, -3.3526e-02, -1.1994e+00,
          -2.6408e+00, -1.5216e+00,  1.9130e+00, -4.7605e-01, -5.6118e-01,
           1.1026e+00,  6.6999e-02,  8.3161e-01, -1.3363e+00, -1.3802e+00,
          -1.6574e+00,  8.5512e-01,  2.4452e-01,  6.5769e-01,  7.0392e-01],
         [-3.9147e-01, -9.4889e-01,  3.2977e-01, -5.1076e-01, -4.3355e-01,
           3.0092e-02, -3.9298e-01,  1.2473e+00,  6.5288e-01, -9.8916e-02,
           1.5547e+00, -1.0847e+00,  2.9859e-01,  7.5193e-01,  3.1574e-01,
          -1.0448e+00,  4.1648e-01,  7.5041e-01,  5.3393e-01, -4.5592e-01],
         [-2.0085e+00,  5.7682e-01,  8.9555e-02,  3.0557e+00, -1.1237e+00,
           1.7974e+00,  1.2420e+00, -1.1231e+00,  8.8847e-01, -2.8549e-01,
           8.4361e-01,  1.2533e-02,  8.8355e-01, -1.2398e+00,  2.0680e+00,
          -6.5193e-01,  5.9728e-01,  2.9683e-01, -9.2126e-01, -5.4479e-01],
         [-5.6075e-01, -1.6989e+00, -6.4249e-01,  2.6394e-01, -1.4793e+00,
           5.6319e-01,

In [28]:
sum(torch.nn.Embedding(corpus_size,embedding_length)(torch.tensor([1,2,3,4])))

tensor([-3.4063,  2.1120,  0.8684, -2.1099,  3.3157, -1.4327,  0.3446, -0.8174,
         1.4776,  1.0483,  1.6590, -0.0110, -5.0981,  2.1633,  0.4413,  0.7242,
        -3.0269, -1.8426,  2.4800, -0.9646], grad_fn=<AddBackward0>)

In [29]:
sum(torch.nn.Embedding(corpus_size,embedding_length)(torch.tensor([1,2,3,4]))).view(1,-1)

tensor([[ 1.0582, -0.1858,  0.1145,  0.4990,  1.7603, -2.6818,  2.9295,  0.8531,
         -1.5743, -1.1967,  2.2516, -1.6370,  0.1689, -0.1428, -2.2309, -2.1129,
          0.2346, -0.1586, -2.0285, -0.2637]], grad_fn=<ViewBackward>)

In [30]:
sum(torch.nn.Embedding(corpus_size,embedding_length)(torch.tensor([1,2,3,4])))

tensor([-2.5890, -0.9532, -0.3505, -0.9481,  3.9521, -1.2958,  0.4861,  0.7157,
         0.9460,  0.3517, -0.9768, -0.1033,  4.7736, -2.8354,  1.9788,  0.3213,
         2.7812, -0.0119, -3.1036,  0.9705], grad_fn=<AddBackward0>)

In [31]:
data

[(['how', 'that', 'haunted', 'my'], 'personage'),
 (['that', 'personage', 'my', 'dreams'], 'haunted'),
 (['personage', 'haunted', 'dreams', 'i'], 'my'),
 (['haunted', 'my', 'i', 'need'], 'dreams'),
 (['my', 'dreams', 'need', 'scarcely'], 'i'),
 (['dreams', 'i', 'scarcely', 'tell'], 'need'),
 (['i', 'need', 'tell', 'you'], 'scarcely'),
 (['need', 'scarcely', 'you', 'on'], 'tell'),
 (['scarcely', 'tell', 'on', 'stormy'], 'you'),
 (['tell', 'you', 'stormy', 'nights'], 'on'),
 (['you', 'on', 'nights', 'when'], 'stormy'),
 (['on', 'stormy', 'when', 'the'], 'nights'),
 (['stormy', 'nights', 'the', 'wind'], 'when'),
 (['nights', 'when', 'wind', 'shook'], 'the'),
 (['when', 'the', 'shook', 'the'], 'wind'),
 (['the', 'wind', 'the', 'four'], 'shook'),
 (['wind', 'shook', 'four', 'corners'], 'the'),
 (['shook', 'the', 'corners', 'of'], 'four'),
 (['the', 'four', 'of', 'the'], 'corners'),
 (['four', 'corners', 'the', 'house'], 'of'),
 (['corners', 'of', 'house', 'and'], 'the'),
 (['of', 'the', 'an

In [33]:
class CBOW(nn.Module):
  def __init__(self,corpus_size,embedding_length):
    super().__init__()

    self.embeddings = nn.Embedding(corpus_size,embedding_length)

    self.linear1 = nn.Linear(embedding_length,64)
    self.linear2 = nn.Linear(64,corpus_size)

    self.activation1 = nn.ReLU()
    self.activation2 = nn.LogSoftmax(dim = -1)

  def forward(self,inputs):
    embed = sum(self.embeddings(inputs)).view(1,-1)
    out = self.linear1(embed)
    out = self.activation1(out)
    out = self.linear2(out)
    out = self.activation2(out)
    return out

  def word_embeddings(self,word):
    vec = torch.LongTensor([word_dict[word]])
    return self.embeddings(vec).view(1,-1)

In [34]:
model = CBOW(corpus_size,embedding_length)

loss_fn = nn.NLLLoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)

In [35]:
for name,params in model.named_parameters():
  print(name)
  print(params)
  print(params.shape)

embeddings.weight
Parameter containing:
tensor([[ 0.0245,  0.0562,  0.1987,  ...,  1.2909,  0.8497,  0.5664],
        [ 0.4826,  0.9972, -1.0322,  ...,  1.2511, -0.1564, -0.1982],
        [-0.5314,  0.6886, -0.1842,  ...,  1.3001, -2.2887, -1.3858],
        ...,
        [ 0.8582, -0.2235,  1.1606,  ..., -0.6164, -0.1084, -1.1073],
        [ 0.0292,  0.0321,  0.3374,  ..., -1.5118, -0.5207,  0.7614],
        [-1.9555,  0.4073, -0.4052,  ..., -0.6620,  0.0905,  1.2438]],
       requires_grad=True)
torch.Size([82, 20])
linear1.weight
Parameter containing:
tensor([[-0.0405,  0.2220,  0.0714,  ..., -0.0670, -0.0138,  0.1318],
        [-0.0671, -0.1040, -0.1915,  ..., -0.0027,  0.1698,  0.0800],
        [ 0.1413,  0.1060, -0.0882,  ...,  0.2036,  0.0304,  0.0190],
        ...,
        [ 0.0960,  0.1349, -0.0932,  ..., -0.0598, -0.1432, -0.0518],
        [-0.0084, -0.1042, -0.0549,  ...,  0.1705,  0.1563, -0.0109],
        [ 0.1777,  0.0216, -0.0617,  ..., -0.2234,  0.1971, -0.0194]],
       

In [36]:
def make_sen_vec(sentence):
  idxs = [word_dict[word] for word in sentence]
  return torch.tensor(idxs,dtype=torch.long)

In [37]:
model(make_sen_vec("now at the hip".lower().split()))

tensor([[-4.1099, -4.2783, -5.0906, -4.5268, -4.7534, -4.2517, -4.0038, -4.7617,
         -4.9739, -4.3370, -5.1192, -4.9286, -4.4956, -4.5664, -4.1958, -5.4568,
         -4.7509, -4.9898, -4.3157, -3.6306, -3.6139, -4.1814, -5.5190, -4.1337,
         -4.1502, -4.1703, -4.1569, -5.2011, -4.8578, -4.0927, -4.7180, -4.9962,
         -4.7143, -4.4045, -5.3187, -5.1486, -4.5726, -4.3171, -4.7410, -4.2179,
         -4.3942, -5.0480, -4.3955, -4.5874, -5.2203, -3.4293, -3.4846, -3.9885,
         -4.6672, -5.2360, -3.7129, -3.6769, -4.8233, -4.6448, -4.5582, -3.6164,
         -4.1453, -4.9906, -5.2006, -4.1783, -4.9285, -5.3316, -4.8852, -4.4085,
         -5.3684, -3.8080, -5.1323, -5.1751, -3.6871, -4.2064, -5.4131, -4.0130,
         -4.7118, -4.0719, -4.3278, -4.4245, -4.8908, -4.6561, -4.4453, -4.0260,
         -4.9623, -4.4947]], grad_fn=<LogSoftmaxBackward>)

In [38]:
model(make_sen_vec("now at the hip".lower().split()))

tensor([[-4.1099, -4.2783, -5.0906, -4.5268, -4.7534, -4.2517, -4.0038, -4.7617,
         -4.9739, -4.3370, -5.1192, -4.9286, -4.4956, -4.5664, -4.1958, -5.4568,
         -4.7509, -4.9898, -4.3157, -3.6306, -3.6139, -4.1814, -5.5190, -4.1337,
         -4.1502, -4.1703, -4.1569, -5.2011, -4.8578, -4.0927, -4.7180, -4.9962,
         -4.7143, -4.4045, -5.3187, -5.1486, -4.5726, -4.3171, -4.7410, -4.2179,
         -4.3942, -5.0480, -4.3955, -4.5874, -5.2203, -3.4293, -3.4846, -3.9885,
         -4.6672, -5.2360, -3.7129, -3.6769, -4.8233, -4.6448, -4.5582, -3.6164,
         -4.1453, -4.9906, -5.2006, -4.1783, -4.9285, -5.3316, -4.8852, -4.4085,
         -5.3684, -3.8080, -5.1323, -5.1751, -3.6871, -4.2064, -5.4131, -4.0130,
         -4.7118, -4.0719, -4.3278, -4.4245, -4.8908, -4.6561, -4.4453, -4.0260,
         -4.9623, -4.4947]], grad_fn=<LogSoftmaxBackward>)

In [39]:
make_sen_vec("now at the hip".lower().split())

tensor([59, 56, 36, 69])

In [40]:
for epoch in range(101):
  epoch_loss = 0
  for sen,lab in data:
    model.zero_grad()
    vec = make_sen_vec(sen)
    log_prob = model(vec)
    loss = loss_fn(log_prob,torch.tensor([word_dict[lab]],dtype=torch.long))
    loss.backward()
    optimizer.step()
    epoch_loss += loss

  print("epoch",epoch,"loss",epoch_loss.item())  

epoch 0 loss 534.7217407226562
epoch 1 loss 476.39422607421875
epoch 2 loss 431.9459228515625
epoch 3 loss 391.6987609863281
epoch 4 loss 352.23529052734375
epoch 5 loss 313.192138671875
epoch 6 loss 274.14691162109375
epoch 7 loss 236.0607452392578
epoch 8 loss 199.5802459716797
epoch 9 loss 166.02828979492188
epoch 10 loss 135.94754028320312
epoch 11 loss 109.90399932861328
epoch 12 loss 87.92127990722656
epoch 13 loss 70.32707977294922
epoch 14 loss 56.485984802246094
epoch 15 loss 45.74825668334961
epoch 16 loss 37.5090446472168
epoch 17 loss 31.18000030517578
epoch 18 loss 26.293272018432617
epoch 19 loss 22.441608428955078
epoch 20 loss 19.401817321777344
epoch 21 loss 17.000070571899414
epoch 22 loss 15.045479774475098
epoch 23 loss 13.46396255493164
epoch 24 loss 12.139389038085938
epoch 25 loss 11.045204162597656
epoch 26 loss 10.104161262512207
epoch 27 loss 9.307291030883789
epoch 28 loss 8.615023612976074
epoch 29 loss 8.009235382080078
epoch 30 loss 7.479128837585449
epoch

In [41]:
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize 
from nltk.corpus import stopwords
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
nltk.download('gutenberg')
nltk.download('punkt')

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [46]:
emma = nltk.corpus.gutenberg.sents('austen-emma.txt')

emma_sentences = []
emma_word_set = []

for sentence in emma:
    emma_sentences.append([word.lower() for word in sentence if word.isalpha()])
    for word in sentence:
        if word.isalpha():
            emma_word_set.append(word.lower())

emma_word_set = set(emma_word_set)

In [47]:
print(emma_word_set)
print(emma_sentences)

{'unequivocal', 'hitherto', 'exclaim', 'busy', 'reaching', 'ringing', 'mental', 'pretending', 'blunder', 'conceited', 'becoming', 'blushes', 'concealed', 'slumbering', 'exulting', 'sobering', 'twelvemonth', 'indiscreetly', 'recovering', 'varieties', 'prime', 's', 'sometimes', 'inadequate', 'extenuation', 'deficiencies', 'in', 'baronne', 'discussion', 'stationary', 'welcomed', 'accents', 'walking', 'continual', 'venture', 'tooth', 'affairs', 'league', 'mildness', 'errantry', 'abhorred', 'papas', 'propose', 'term', 'hints', 'playing', 'confession', 'lectured', 'blamed', 'spirits', 'ever', 'mimic', 'fed', 'vexation', 'blended', 'care', 'perpetual', 'diffuse', 'remarks', 'peculiarly', 'combine', 'mark', 'ireland', 'appeal', 'styles', 'greatest', 'thanking', 'undervalued', 'importance', 'resolved', 'really', 'used', 'aimed', 'privileged', 'bore', 'distinction', 'restrain', 'article', 'rapidly', 'littleness', 'stranger', 'recommending', 'report', 'missed', 'unexpected', 'finishing', 'choice'

In [48]:
def TermFreq(document, word):
    doc_length = len(document)
    occurances = len([w for w in document if w == word])
    return occurances / doc_length

TermFreq(emma_sentences[5], 'ago')

0.024390243902439025

In [49]:
def build_DF_dict():
    output = {}
    for word in emma_word_set:
        output[word] = 0
        for doc in emma_sentences:
            if word in doc:
                output[word] += 1
    return output
        
df_dict = build_DF_dict()

df_dict['ago']

32

In [50]:
def InverseDocumentFrequency(word):
 N = len(emma_sentences)
 try:
  df = df_dict[word] + 1
 except:
  df = 1
 return np.log(N/df)
InverseDocumentFrequency('ago')

5.459198592104122

In [51]:
def TFIDF(doc, word):
 tf = TermFreq(doc, word)
 idf = InverseDocumentFrequency(word)
 return tf*idf
print('ago - ' + str(TFIDF(emma_sentences[5],'ago')))
print('indistinct - ' + str(TFIDF(emma_sentences[5],'indistinct')))

ago - 0.13315118517327126
indistinct - 0.20152582861001603


In [57]:
model.word_embeddings('paid')

tensor([[ 1.3811,  1.5718,  1.5119, -1.3157, -1.1234,  0.5470,  1.7123,  0.8264,
         -0.6595, -1.5464, -0.0348, -0.5823,  1.4860, -0.5287,  0.8081,  0.1127,
          0.6269,  1.6461,  0.8101,  0.8275]], grad_fn=<ViewBackward>)

In [60]:
embeddings = []
for word in emma_sentences[5]:
 embeddings.append(model[word])
mean_embedding = np.mean(embeddings, axis = 0).reshape(1, -1)
print(mean_embedding)

[[ 3.32575634e-01  3.16596488e-01 -1.80050732e-01 -3.82070951e-01
   4.98493527e-01  5.33804805e-01 -5.46517073e-01  9.12476195e-02
  -1.31538483e-01 -2.71967805e-02  2.99867317e-02  2.64278024e-02
  -2.06519756e-01 -1.54796634e-01  4.28036366e-01 -5.74977317e-02
  -2.65928778e-01  1.60373902e-02 -2.84913561e-01 -2.01252268e-01
  -5.96390732e-02  5.72458220e-01  2.06195927e-01 -1.54312293e-01
   2.52049805e-01 -1.64638200e+00 -3.42686049e-01  1.02592522e-01
   1.42848000e-01 -1.09779902e-01  2.89345488e+00  7.36985634e-02
  -3.73648780e-03 -2.76292784e-01  1.50580049e-01  9.80399951e-02
   2.24408780e-03  2.83664024e-01  3.92979024e-02 -2.98091634e-01
  -1.17309171e-01  2.08815776e-01  6.89953902e-03  2.92777244e-02
   5.54180122e-02 -2.20519707e-01 -2.82007805e-01 -4.34917439e-01
  -9.69051537e-02 -1.67569878e-01]]


In [62]:
embeddings = []
for word in emma_sentences[5]:
 tfidf = TFIDF(emma_sentences[5], word)

embeddings.append(model[word]* tfidf)

tfidf_weighted_embedding = np.mean(embeddings, axis = 0).reshape(1, -1)
print(tfidf_weighted_embedding)

[[ 0.00561251  0.19113099 -0.07834439 -0.03203354  0.12825717  0.11851425
   0.03289712  0.06451117 -0.03105187  0.12906908  0.04065701  0.08219235
   0.07404619 -0.11115786 -0.03780056 -0.01310373 -0.03631944  0.03661222
   0.02216391 -0.06132627 -0.05206926  0.1447045  -0.00794294 -0.05733438
   0.14408942 -0.09502422 -0.07860273  0.02590608  0.11575007  0.00287773
   0.12044561  0.19776159  0.07065339 -0.08990796 -0.0560833  -0.02411865
  -0.08615103 -0.0352861  -0.09175075 -0.046798    0.10129438  0.01179213
  -0.08586563  0.05590615  0.01248742 -0.03237553 -0.07146038 -0.02489734
  -0.05164978 -0.0375533 ]]


In [63]:
cosine_similarity(mean_embedding, tfidf_weighted_embedding)

array([[0.44517081]])

In [2]:
with open("/content/amazon_cells_labelled.txt") as f:
  reviews = f.read()

In [3]:
reviews

'So there is no way for me to plug it in here in the US unless I go by a converter.\t0\nGood case, Excellent value.\t1\nGreat for the jawbone.\t1\nTied to charger for conversations lasting more than 45 minutes.MAJOR PROBLEMS!!\t0\nThe mic is great.\t1\nI have to jiggle the plug to get it to line up right to get decent volume.\t0\nIf you have several dozen or several hundred contacts, then imagine the fun of sending each of them one by one.\t0\nIf you are Razr owner...you must have this!\t1\nNeedless to say, I wasted my money.\t0\nWhat a waste of money and time!.\t0\nAnd the sound quality is great.\t1\nHe was very impressed when going from the original battery to the extended battery.\t1\nIf the two were seperated by a mere 5+ ft I started to notice excessive static and garbled sound from the headset.\t0\nVery good quality though\t1\nThe design is very odd, as the ear "clip" is not very comfortable at all.\t0\nHighly recommend for any one who has a blue tooth phone.\t1\nI advise EVERYON

In [4]:
df = pd.DataFrame([review.split('\t') for review in reviews.split('\n')])
df.columns = ['Review','Sentiment']
df

Review Sentiment
0     So there is no way for me to plug it in here i...         0
1                           Good case, Excellent value.         1
2                                Great for the jawbone.         1
3     Tied to charger for conversations lasting more...         0
4                                     The mic is great.         1
...                                                 ...       ...
996   What a piece of junk.. I lose more calls on th...         0
997                        Item Does Not Match Picture.         0
998   The only thing that disappoint me is the infra...         0
999   You can not answer calls with the unit, never ...         0
1000                                                         None

[1001 rows x 2 columns]

In [8]:
import pandas as pd
from string import punctuation
import numpy as np
import torch
from nltk.tokenize import word_tokenize
from torch.utils.data import TensorDataset, DataLoader
from torch import nn
from torch import optim
import json
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [19]:
def split_words_reviews(data):
 text = list(data['Review'].values)
 clean_text = []
 for t in text:
    clean_text.append(t.translate(str.maketrans('', '',punctuation)).lower().rstrip())
    tokenized = [word_tokenize(x) for x in clean_text]
    all_text = []
    for tokens in tokenized:
      for t in tokens:
        all_text.append(t)
 return tokenized, set(all_text)

reviews, vocab = split_words_reviews(df)
reviews

[['so',
  'there',
  'is',
  'no',
  'way',
  'for',
  'me',
  'to',
  'plug',
  'it',
  'in',
  'here',
  'in',
  'the',
  'us',
  'unless',
  'i',
  'go',
  'by',
  'a',
  'converter'],
 ['good', 'case', 'excellent', 'value'],
 ['great', 'for', 'the', 'jawbone'],
 ['tied',
  'to',
  'charger',
  'for',
  'conversations',
  'lasting',
  'more',
  'than',
  '45',
  'minutesmajor',
  'problems'],
 ['the', 'mic', 'is', 'great'],
 ['i',
  'have',
  'to',
  'jiggle',
  'the',
  'plug',
  'to',
  'get',
  'it',
  'to',
  'line',
  'up',
  'right',
  'to',
  'get',
  'decent',
  'volume'],
 ['if',
  'you',
  'have',
  'several',
  'dozen',
  'or',
  'several',
  'hundred',
  'contacts',
  'then',
  'imagine',
  'the',
  'fun',
  'of',
  'sending',
  'each',
  'of',
  'them',
  'one',
  'by',
  'one'],
 ['if', 'you', 'are', 'razr', 'owneryou', 'must', 'have', 'this'],
 ['needless', 'to', 'say', 'i', 'wasted', 'my', 'money'],
 ['what', 'a', 'waste', 'of', 'money', 'and', 'time'],
 ['and', 'the

In [20]:
def create_dictionaries(words):
 word_to_int_dict = {w:i+1 for i, w in enumerate(words)}
 int_to_word_dict = {i:w for w, i in word_to_int_dict.
 items()}
 return word_to_int_dict, int_to_word_dict
word_to_int_dict, int_to_word_dict = create_dictionaries(vocab)
int_to_word_dict

{1: 'today',
 2: 'commercials',
 3: 'gadget',
 4: 'ericson',
 5: 'speakerphone',
 6: 'greatno',
 7: 'unacceptible',
 8: 'speed',
 9: 'hundred',
 10: 'handy',
 11: 'totally',
 12: 'europe',
 13: 'went',
 14: 'items',
 15: 'buttons',
 16: 'infuriating',
 17: 'onlyi',
 18: 'conversations',
 19: 'protector',
 20: 'megapixels',
 21: 'coming',
 22: 'disappointment',
 23: 'gadgets',
 24: 'cradles',
 25: 'outgoing',
 26: 'id',
 27: 'wellwell',
 28: 'ticking',
 29: 'instruction',
 30: 'detailed',
 31: 'basement',
 32: 'during',
 33: 'lightweight',
 34: 'mp3',
 35: 'family',
 36: 'discarded',
 37: 'slide',
 38: 'any',
 39: 'elegant',
 40: 'sync',
 41: 'wake',
 42: 'unless',
 43: 'reach',
 44: 'colored',
 45: 'sure',
 46: 'wiping',
 47: 'unintelligible',
 48: 'feet',
 49: 'avoiding',
 50: 'received',
 51: 'buyerbe',
 52: 'compromise',
 53: 'majority',
 54: 'outside',
 55: 'between',
 56: 'cut',
 57: 'creaks',
 58: 'provide',
 59: 'issues',
 60: 'videos',
 61: 'only',
 62: 'falling',
 63: 'smoothe

In [21]:
print(np.max([len(x) for x in reviews]))
print(np.mean([len(x) for x in reviews]))

30
10.202


In [22]:
def pad_text(tokenized_reviews, seq_length):

 reviews = []

 for review in tokenized_reviews:
    if len(review) >= seq_length:
      reviews.append(review[:seq_length])
    else:
      reviews.append(['']*(seq_length-len(review)) + review)

 return np.array(reviews)
 
padded_sentences = pad_text(reviews, seq_length = 50)
padded_sentences[0]

array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', 'so', 'there',
       'is', 'no', 'way', 'for', 'me', 'to', 'plug', 'it', 'in', 'here',
       'in', 'the', 'us', 'unless', 'i', 'go', 'by', 'a', 'converter'],
      dtype='<U22')

In [23]:
int_to_word_dict[0] = ''
word_to_int_dict[''] = 0

In [24]:
encoded_sentences = np.array([[word_to_int_dict[word] for word in review] for review in padded_sentences])
encoded_sentences[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0, 1104,  898,  139,  196,
       1380, 1108, 1752,  743,  835,  512,  263, 1902,  263,  258,  663,
         42, 1795, 1850,  873,  714,  201])

In [34]:
class sentiment_lstm(nn.Module):
  
  def __init__(self,n_vocab,n_embed,n_hidden,n_output,n_layers,drop_p = 0.8):
    super().__init__()
    self.n_vocab = n_vocab
    self.n_layers = n_layers
    self.n_hidden = n_hidden 
    self.embed = nn.Embedding(n_vocab,n_embed)
    self.lstm = nn.LSTM(n_embed,n_hidden,n_layers,batch_first = True,dropout = drop_p)
    self.dropout = nn.Dropout(drop_p)
    self.fc = nn.Linear(n_hidden,n_output)
    self.sigmoid = nn.Sigmoid()

  def forward(self,input_words):
    embedded_words = self.embed(input_words)
    lstm_out, h = self.lstm(embedded_words)
    lstm_out = self.dropout(lstm_out)
    lstm_out = lstm_out.contiguous().view(-1,self.n_hidden)
    fc_out = self.fc(lstm_out)
    sigmoid_out = self.sigmoid(fc_out)
    sigmoid_out = sigmoid_out.view(batch_size, -1)
    sigmoid_last = sigmoid_out[:, -1]
    return sigmoid_last, h

  def init_hidden (self, batch_size):
    device = "cpu"
    weights = next(self.parameters()).data
    h = (weights.new(self.n_layers, batch_size,self.n_hidden).zero_().to(device),weights.new(self.n_layers, batch_size,self.n_hidden).zero_().to(device))
    return h

In [35]:
n_vocab = len(word_to_int_dict)
n_embed = 50
n_hidden = 100
n_output = 1
n_layers = 2
net = sentiment_lstm(n_vocab, n_embed, n_hidden, n_output,n_layers)

In [36]:
for name,params in net.named_parameters():
  print(name)
  print(params.shape)
  print(params)

embed.weight
torch.Size([1906, 50])
Parameter containing:
tensor([[ 0.2346,  0.0205, -1.2716,  ..., -0.4294,  1.7744, -1.2168],
        [ 0.0376, -0.2998,  0.2011,  ...,  1.2595,  1.6830,  0.0818],
        [-3.0014, -0.7527, -1.6007,  ..., -0.9318,  0.1955, -1.0147],
        ...,
        [-0.9509,  1.8944, -1.0993,  ..., -0.3897,  0.5563,  0.6677],
        [ 1.0575,  0.5761, -0.9093,  ...,  0.0425, -1.2757, -2.0131],
        [ 1.4257, -0.3916, -0.5250,  ..., -1.4595, -0.2205, -0.0376]],
       requires_grad=True)
lstm.weight_ih_l0
torch.Size([400, 50])
Parameter containing:
tensor([[ 0.0929, -0.0019, -0.0947,  ..., -0.0314, -0.0188,  0.0265],
        [-0.0243,  0.0333,  0.0990,  ..., -0.0344, -0.0348,  0.0722],
        [-0.0832,  0.0274, -0.0088,  ..., -0.0494, -0.0573,  0.0028],
        ...,
        [-0.0056, -0.0923, -0.0270,  ...,  0.0142,  0.0634, -0.0957],
        [-0.0037, -0.0067,  0.0691,  ..., -0.0786,  0.0530, -0.0617],
        [-0.0797, -0.0006, -0.0582,  ..., -0.0227, -0.01

In [25]:
df = df.dropna()
labels = np.array([int(x) for x in df['Sentiment'].values])
labels

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [40]:
train_ratio = 0.8
valid_ratio = (1 - train_ratio)/2

labels = np.array([int(label) for label in df['Sentiment']])
labels

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [27]:
total = len(encoded_sentences)
train_cutoff = int(total * train_ratio)
valid_cutoff = int(total * (1 - valid_ratio))
train_x, train_y = torch.Tensor(encoded_sentences[:train_cutoff]).long(), torch.Tensor(labels[:train_cutoff]).long()
valid_x, valid_y = torch.Tensor(encoded_sentences[train_cutoff : valid_cutoff]).long(), torch.Tensor(labels[train_cutoff : valid_cutoff]).long()
test_x, test_y = torch.Tensor(encoded_sentences[valid_cutoff:]).long(), torch.Tensor(labels[valid_cutoff:])
train_data = TensorDataset(train_x, train_y)
valid_data = TensorDataset(valid_x, valid_y)
test_data = TensorDataset(test_x, test_y)

In [28]:
batch_size = 1
train_loader = DataLoader(train_data, batch_size = batch_size,
 shuffle = True)
valid_loader = DataLoader(valid_data, batch_size = batch_size,
 shuffle = True)
test_loader = DataLoader(test_data, batch_size = batch_size,
 shuffle = True)

In [29]:
print_every = 2400
step = 0
n_epochs = 3
clip = 5
criterion = nn.BCELoss()
optimizer = optim.Adam(net.parameters(), lr = 0.001)

In [82]:
for epoch in range(n_epochs):
    h = net.init_hidden(batch_size)
    
    for inputs, labels in train_loader:
        step += 1  
        net.zero_grad()
        output, h = net(inputs)
        loss = criterion(output, labels.float())
        loss.backward()
        nn.utils.clip_grad_norm(net.parameters(), clip)
        optimizer.step()
        
        if (step % print_every) == 0:            
            net.eval()
            valid_losses = []

            for v_inputs, v_labels in valid_loader:
                       
                v_output, v_h = net(v_inputs)
                v_loss = criterion(v_output, v_labels.float())
                valid_losses.append(v_loss.item())

            print("Epoch: {}/{}".format((epoch+1), n_epochs),
                  "Step: {}".format(step),
                  "Training Loss: {:.4f}".format(loss.item()),
                  "Validation Loss: {:.4f}".format(np.mean(valid_losses)))
            net.train()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  # Remove the CWD from sys.path while we load stuff.


Epoch: 1/3 Step: 12000 Training Loss: 0.7083 Validation Loss: 0.6922


In [83]:
torch.save(net.state_dict(), 'model.pkl')

In [44]:
labels

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [62]:
o,h = net(torch.tensor(encoded_sentences[0]).view(1,-1))

In [63]:
print(o)

tensor([0.5010], grad_fn=<SelectBackward>)


In [72]:
print(h[0].shape)
print(h[1].shape)

torch.Size([2, 1, 100])
torch.Size([2, 1, 100])


In [52]:
i = 0;
for inputs,labels in train_loader:
  print(inputs)

tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
         1606, 1062]])
tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,  754,  139,  714,
         1606, 1552]])
tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0, 

In [59]:
tfd = torch.tensor(encoded_sentences[0])
tfd.view(1,-1)

tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0, 1104,  898,  139,  196, 1380, 1108, 1752,
          743,  835,  512,  263, 1902,  263,  258,  663,   42, 1795, 1850,  873,
          714,  201]])

In [85]:
net.eval()
test_losses = []
num_correct = 0
for inputs, labels in test_loader:
 test_output, test_h = net(inputs)
 loss = criterion(test_output, labels)
 test_losses.append(loss.item())

 preds = torch.round(test_output.squeeze())
 correct_tensor = preds.eq(labels.float().view_as(preds))
 correct = np.squeeze(correct_tensor.numpy())
 num_correct += np.sum(correct)

print("Test Loss: {:.4f}".format(np.mean(test_losses)))
print("Test Accuracy: {:.2f}".format(num_correct/len(test_loader.dataset)))

Test Loss: 0.6881
Test Accuracy: 0.58


In [99]:
def preprocess_review(review):
    review = review.translate(str.maketrans('', '', punctuation)).lower().rstrip()
    tokenized = word_tokenize(review)
    if len(tokenized) >= 50:
        review = tokenized[:50]
    else:
        review= ['0']*(50-len(tokenized)) + tokenized
    
    final = []
    
    for token in review:
        try:
            final.append(word_to_int_dict[token])
            
        except:
            final.append(word_to_int_dict[''])
        
    return final

In [100]:
preprocess_review(df.loc[0]['Review'])

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1104,
 898,
 139,
 196,
 1380,
 1108,
 1752,
 743,
 835,
 512,
 263,
 1902,
 263,
 258,
 663,
 42,
 1795,
 1850,
 873,
 714,
 201]

In [101]:
def predict(review):
    net.eval()
    words = np.array([preprocess_review(review)])
    padded_words = torch.from_numpy(words)
    pred_loader = DataLoader(padded_words, batch_size = 1, shuffle = True)
    for x in pred_loader:
        output = net(x)[0].item()
    
    msg = "This is a positive review." if output >= 0.5 else "This is a negative review."
    print(msg)
    print('Prediction = ' + str(output))

In [102]:
predict("The film was good")

This is a negative review.
Prediction = 0.48553985357284546


In [104]:
predict("It was not good")

This is a negative review.
Prediction = 0.4855002462863922
